# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  docker1:
    :hostname: "docker1"
    :ip: "192.168.46.100"
    :ram: 512
    :cpu: 1
    :box: "debian/stretch64"

:groups:
  servers:
    - docker1
