---
# no_log: true
- name: Vagrant Test Playbook
  hosts: servers
  gather_facts: True
  become: yes
  become_method: sudo
  environment:
    SHELL: /bin/bash
  tags:
    - docker
  roles:
    - role: boss-ansible-role-bootstrap
    - role: boss-ansible-role-core
    - role: boss-ansible-role-fact
    - role: boss-ansible-role-environment
    - role: boss-ansible-role-etckeeper
    - role: ../
      bossjones__user: root
      bossjones__group: root
      boss__docker__install_method: shell
