---
- name: Check current docker-compose version.
  command: docker-compose --version
  register: boss__docker__compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ boss__docker__compose_path }}"
    state: absent
  when: >
    boss__docker__compose_current_version.stdout is defined
    and boss__docker__compose_version not in boss__docker__compose_current_version.stdout

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ boss__docker__compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ boss__docker__compose_path }}"
    mode: 0755
