---
dependency:
  name: gilt
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  # source: https://blog.opsfactory.rocks/testing-ansible-roles-with-molecule-97ceca46736a
  # source: https://github.com/solita/docker-systemd
  # source: https://github.com/solita/docker-systemd-ssh/blob/master/Dockerfile
  # start_command: docker run -d --name systemd --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t solita/ubuntu-systemd
  # - name: boss-ansible-role-sysctl-trusty
  #   image: solita/ubuntu-systemd
  #   image_version: latest
  #   privileged: True
  #   groups:
  #       - servers
  #   capabilities:
  #     - SYS_ADMIN
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   command: /sbin/init

  # FIXME: 9/30/2018 this was what we were using!
  # --------------------------------------------
  # - name: boss-ansible-role-sysctl-trusty
  #   image: solita/ubuntu-systemd
  #   image_version: latest
  #   privileged: True
  # --------------------------------------------
  # TODO: Figure out if we want to use geerlingguy docker container or not [BEGIN]
  # --------------------------------------------------------------------------------
  # - name: instance
  #   image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
  #   command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
  #   privileged: true
  #   pre_build_image: true
  # ------------------------------------------------------------------------[END]---
  - name: docker-sysctl1
    image: solita/ubuntu-systemd
    image_version: latest
    privileged: True
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
    groups:
        - servers
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker:/var/lib/docker:rw
      - /var/run/docker.sock:/var/run/docker.sock
    command: /sbin/init
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
  options:
    vvv: True
  lint:
    name: ansible-lint
    enabled: False
    # EANSIBLE0013 should not be raised for shell tasks that use globs.
    options:
      x: ANSIBLE0013
  inventory:
    host_vars:
      docker-sysctl1:
        # SOURCE: https://github.com/osism/ansible-hosts/blob/ce8147623491011269bf15291bd8bf83397ab1ff/molecule/default/molecule.yml
        # NOTE: workaround for https://github.com/moby/moby/issues/22281
        hosts_file: /etc/hosts.molecule
        management_interface: lo0
        inventory_hostname: docker-sysctl1
        inventory_hostname_short: docker-sysctl1
        ansible_lo0:
          ipv4:
            address: 127.0.0.1
        ansible_default_ipv4:
          address: 127.0.1.2
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: True
  lint:
    name: flake8
    enabled: False

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - lint
    - side_effect
    - verify
    - destroy
