---
- name: Converge
  hosts: all
  become: True

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    # - role: bossjones.docker
    - role: boss-ansible-role-docker
